@UrlShortener_HostAddress = http://localhost:5277

POST http://localhost:5277/api/auth/register
Content-Type: application/json

{
  "Email": "Wham@example.com",
  "Password": "Wham@123"
}

###

POST http://localhost:5277/api/url
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2M4YTcwOC1jZTdjLTQxMGItOWFlOS00YzIyMjQwN2Q1ZjgiLCJlbWFpbCI6Im9tZWl6YWFobWVkQGdtYWlsLmNvbSIsImp0aSI6Ijg0NWVhYTA4LTMwZGYtNDM0OS1hYTQ2LTZiMDY0ZWFmYjhiZSIsImZhbWlseV9uYW1lIjoiQWhtZWQiLCJnaXZlbl9uYW1lIjoiT21laXphIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIkFkbWluIiwiVXNlciJdLCJleHAiOjE3ODU5NDI5MTksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTI3NyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTI3NyJ9.Lz3EoZgtOJMQYv-TZzhKjyVYFMYeYjzWsSgTutnp8D8
Content-Type: application/json

{
  "url": "https://www.bing.com/search?pglt=299&q=how+to+make+a+add+in+ef+core+return+the+new+row+added&cvid=8390a5dd354e4c86a427f1fa44c9014e&gs_lcrp=EgRlZGdlKgYIABBFGDkyBggAEEUYOTIHCAEQ6wcYQNIBCTMwNDIyajBqN6gCALACAA&FORM=ANNTA1&PC=W251"
}

###

GET http://localhost:5277/api/url

###

DELETE http://localhost:5277/api/url/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJXaGFtQGV4YW1wbGUuY29tIiwianRpIjoiNGU4NTdmMDgtODdhMi00YzYxLWI2MGEtZjY2ZjNhNzYwZDczIiwicm9sZSI6InVzZXIiLCJleHAiOjE3ODMwOTIzODAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTI3NyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTI3NyJ9.vg-dP-OJq0LURJdfT9Z2T_iI79ErIs4Xn7Yk9OXLV2Y

###

POST http://localhost:5277/api/auth/refresh

###

POST http://localhost:5277/api/auth/login
Content-Type: application/json

{
  "Email": "Wham@example.com",
  "Password": "Wham@123"
}

###


GET http://localhost:5277

###